import {clone, inside, line, fill, resize, validateMap, canStand, History, blankMap} from './core.js';
import {createTileset, tiles, starterMap} from './tiles.js';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const canvas = $('#map-canvas'), ctx = canvas.getContext('2d'), viewport = $('#viewport'), tileset = createTileset();
const history = new History(), KEY = 'wild-strokes-fieldwork-v1', images = new Map();
let map = starterMap(), selected = 0, category = 'ground', layer = 'ground', tool = 'paint';
let visible = {ground:true, objects:true, collision:false}, zoom = 1, grid = false, hover = null, keyboardCell = {x:9,y:12};
let gesture = null, beforeStroke = null, playing = false, player = null, keys = new Set(), space = false, toastTimer, saveTimer, stageFit = true;
const pointers = new Map();
function toast(message) {$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
function autoSave() {clearTimeout(saveTimer);$('#save-status').textContent='Saving…';saveTimer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify(map));$('#save-status').textContent='Saved here';}catch{$('#save-status').textContent='Save JSON copy';toast('Browser storage is full or unavailable. Save a JSON copy to keep this map.');}},350);}
async function imageFrom(data) {if(images.has(data))return images.get(data);const im=new Image();im.src=data;await im.decode();images.set(data,im);return im;}
async function loadCustom(m) {if(!m.custom)return;const im=await imageFrom(m.custom.data);if(im.width!==m.custom.columns*m.custom.size||im.height!==m.custom.rows*m.custom.size)throw Error('Custom image dimensions do not match its grid.');}
function tileInfo(id) {return tiles[id] || {id,name:`Your tile ${id-999}`,layer:category==='objects'?'objects':'ground',solid:false};}
function drawTile(context,id,x,y,size=32) {
  if(id===-1)return;
  if(id<1000){context.drawImage(tileset,(id%8)*32,Math.floor(id/8)*32,32,32,x,y,size,size);return;}
  const custom=map.custom, im=custom&&images.get(custom.data);if(!im)return;const i=id-1000,s=custom.size;
  context.drawImage(im,(i%custom.columns)*s,Math.floor(i/custom.columns)*s,s,s,x,y,size,size);
}
function renderArt(context, layers=visible) {context.imageSmoothingEnabled=false;for(const l of ['ground','objects'])if(layers[l])for(let i=0;i<map.layers[l].length;i++)drawTile(context,map.layers[l][i],(i%map.width)*32,Math.floor(i/map.width)*32);}
function render() {
  ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;
  // The editor's checkerboard and guides never enter exported art.
  for(let y=0;y<map.height;y++)for(let x=0;x<map.width;x++){ctx.fillStyle=(x+y)%2?'#70806a':'#76876e';ctx.fillRect(x*32,y*32,32,32);}
  renderArt(ctx);
  if(!playing&&visible.collision){ctx.fillStyle='#ba594154';for(let i=0;i<map.layers.collision.length;i++)if(map.layers.collision[i]){const x=i%map.width*32,y=Math.floor(i/map.width)*32;ctx.fillRect(x,y,32,32);ctx.strokeStyle='#eaae8977';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+4,y+4);ctx.lineTo(x+28,y+28);ctx.moveTo(x+28,y+4);ctx.lineTo(x+4,y+28);ctx.stroke();}}
  if(grid&&!playing){ctx.beginPath();ctx.strokeStyle='#f1edcf30';ctx.lineWidth=1;for(let x=0;x<=map.width;x++){ctx.moveTo(x*32+.5,0);ctx.lineTo(x*32+.5,canvas.height);}for(let y=0;y<=map.height;y++){ctx.moveTo(0,y*32+.5);ctx.lineTo(canvas.width,y*32+.5);}ctx.stroke();}
  if(!playing){const x=map.spawn.x*32,y=map.spawn.y*32;ctx.fillStyle='#f8e8b8';ctx.fillRect(x+10,y+9,2,18);ctx.fillStyle='#384f40';ctx.fillRect(x+12,y+8,10,8);ctx.fillStyle='#e4b770';ctx.fillRect(x+12,y+9,9,5);ctx.fillStyle='#fbeac4';ctx.fillRect(x+12,y+9,2,5);
    if(gesture?.kind==='rectangle'){const a=gesture.start,b=gesture.last;ctx.fillStyle='#e9ce9260';ctx.strokeStyle='#f7e2af';const x0=Math.min(a.x,b.x)*32,y0=Math.min(a.y,b.y)*32,w=(Math.abs(a.x-b.x)+1)*32,h=(Math.abs(a.y-b.y)+1)*32;ctx.fillRect(x0,y0,w,h);ctx.strokeRect(x0+.5,y0+.5,w-1,h-1);}
    if(hover&&inside(map,hover.x,hover.y)){ctx.strokeStyle=layer==='collision'?'#f2b083':'#ffe0a0';ctx.lineWidth=2;ctx.strokeRect(hover.x*32+1,hover.y*32+1,30,30);}
  }else if(player){
    const x=Math.round(player.x*32),y=Math.round(player.y*32),bob=player.moving?Math.round(Math.sin(player.time*17)):0;
    ctx.fillStyle='#263f3c66';ctx.fillRect(x-7,y+4,14,5);ctx.fillStyle='#614c36';ctx.fillRect(x-5,y,4,7);ctx.fillRect(x+2,y,4,7);ctx.fillStyle='#caaf75';ctx.fillRect(x-6,y-13+bob,12,11);ctx.fillStyle='#7b9a61';ctx.fillRect(x-7,y-10+bob,14,8);ctx.fillStyle='#cf8052';ctx.fillRect(x-7,y-3+bob,14,3);ctx.fillStyle='#e4bf86';ctx.fillRect(x-4,y-12+bob,8,3);ctx.fillStyle='#3a5340';ctx.fillRect(x+1,y-11+bob,2,2);ctx.fillStyle='#829c63';ctx.fillRect(x-5,y-17+bob,10,5);ctx.fillStyle='#b1c183';ctx.fillRect(x-3,y-17+bob,6,1);
  }
}
function dimensions(fit=stageFit) {canvas.width=map.width*32;canvas.height=map.height*32;$('#map-width').value=map.width;$('#map-height').value=map.height;$('#map-name').value=map.name;$('.stage-tag').textContent=map.name.toUpperCase();if(fit)fitMap();else applyZoom();$('#cell-status').textContent=`${map.width} × ${map.height} cells · ${canvas.width} × ${canvas.height} px`;render();}
function applyZoom(){canvas.style.width=`${Math.round(canvas.width*zoom)}px`;canvas.style.height=`${Math.round(canvas.height*zoom)}px`;$('#zoom-label').textContent=`${Math.round(zoom*100)}%`;}
function fitMap(){const pad=innerWidth<601?24:50;zoom=Math.min(2,Math.max(.12,Math.min((viewport.clientWidth-pad)/canvas.width,(viewport.clientHeight-pad)/canvas.height)));stageFit=true;applyZoom();viewport.scrollTop=0;viewport.scrollLeft=0;}
function selectedPreview(){const c=$('#selected-preview').getContext('2d');c.clearRect(0,0,64,64);c.imageSmoothingEnabled=false;drawTile(c,selected,0,0,64);const t=tileInfo(selected);$('#tile-name').textContent=t.name;$('#tile-type').textContent=`${selected>=1000?'CUSTOM':t.layer.toUpperCase()} / 32 × 32`;$$('.tile').forEach(b=>{const on=Number(b.dataset.id)===selected;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});}
function palette(){const panel=$('#palette');panel.replaceChildren();const ids=category==='custom'?(map.custom?Array.from({length:map.custom.columns*map.custom.rows},(_,i)=>i+1000):[]):tiles.filter(t=>t.layer===category).map(t=>t.id);$('#tile-count').textContent=`${ids.length} pieces`;
  if(!ids.length){const p=document.createElement('p');p.className='empty';p.textContent='Your tiles live here. Import a tilesheet below to make this world your own.';panel.append(p);}
  for(const id of ids){const t=tileInfo(id),b=document.createElement('button');b.className='tile';b.title=t.name+(t.solid?' · solid':'');b.setAttribute('aria-label',t.name);b.dataset.id=id;const c=document.createElement('canvas');c.width=c.height=32;c.getContext('2d').imageSmoothingEnabled=false;drawTile(c.getContext('2d'),id,0,0);b.append(c);b.onclick=()=>{if(playing)return;selected=id;if(id<1000)setLayer(t.layer);else if(layer==='collision')setLayer('ground');if(tool==='pick'||tool==='spawn'||tool==='erase')setTool('paint');selectedPreview();};panel.append(b);}
  $$('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===category));selectedPreview();
}
function setTool(value){tool=value;$$('[data-tool]').forEach(b=>{const on=b.dataset.tool===tool;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});$('#tool-status').textContent=({paint:layer==='collision'?'Collision · drag to block':'Paint · drag to draw',erase:'Erase · drag to remove',fill:'Fill · click a connected area',rectangle:'Rectangle · drag a filled region',pick:'Pick · click a tile to select it',spawn:'Spawn · click a walkable tile'})[tool];}
function setLayer(value){if(playing)return;layer=value;$$('[data-layer-row]').forEach(b=>b.classList.toggle('active',b.dataset.layerRow===layer));$$('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layer===layer)));if(layer==='collision'){visible.collision=true;syncVisibility();}setTool(tool);render();}
function syncVisibility(){$$('[data-visible]').forEach(b=>{const on=visible[b.dataset.visible];b.textContent=on?'◉':'○';b.setAttribute('aria-pressed',String(on));});}
function syncHistory(){$('#undo').disabled=!history.past.length||playing;$('#redo').disabled=!history.future.length||playing;}
function finishChange(before,message){if(history.commit(before,map)){syncHistory();autoSave();render();if(message)toast(message);}}
function autoCollision(i){if(!$('#auto-solid').checked)return;map.layers.collision[i]=Number([map.layers.ground[i],map.layers.objects[i]].some(id=>tiles[id]?.solid));}
function writeCell(x,y,erase=false){if(!inside(map,x,y))return;const i=y*map.width+x;if(layer==='collision')map.layers.collision[i]=erase?0:1;else{map.layers[layer][i]=erase?-1:selected;autoCollision(i);}}
function pickCell(p){let id=map.layers[layer]?.[p.y*map.width+p.x];if(layer==='collision')id=map.layers.objects[p.y*map.width+p.x]!==-1?map.layers.objects[p.y*map.width+p.x]:map.layers.ground[p.y*map.width+p.x];if(id===-1){toast('That cell is empty on this layer.');return;}selected=id;category=id>=1000?'custom':tiles[id].layer;if(layer==='collision')setLayer(id>=1000?'ground':tiles[id].layer);palette();setTool('paint');}
function applySingle(p,erase=false){const before=clone(map);if(tool==='pick'&&!erase){pickCell(p);return;}if(tool==='spawn'&&!erase){if(!canStand(map,p.x+.5,p.y+.5)){toast('Choose an unblocked tile for the spawn.');return;}map.spawn={...p};}else if(tool==='fill'&&!erase){fill(map,layer,p.x,p.y,layer==='collision'?1:selected);if(layer!=='collision'&&$('#auto-solid').checked)for(let i=0;i<map.layers.ground.length;i++)if(before.layers[layer][i]!==map.layers[layer][i])autoCollision(i);}else writeCell(p.x,p.y,erase||tool==='erase');finishChange(before);render();}
function point(event){const r=canvas.getBoundingClientRect();return{x:Math.floor((event.clientX-r.left)*map.width/r.width),y:Math.floor((event.clientY-r.top)*map.height/r.height)};}
function begin(e){if(e.button>2)return;if(playing){canvas.focus({preventScroll:true});return;}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);
  if(pointers.size===2){finishStroke();const a=[...pointers.values()];gesture={kind:'touchpan',start:{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2},scroll:{x:viewport.scrollLeft,y:viewport.scrollTop}};return;}
  canvas.focus({preventScroll:true});const p=point(e);if(space||e.button===1){gesture={kind:'pan',start:{x:e.clientX,y:e.clientY},scroll:{x:viewport.scrollLeft,y:viewport.scrollTop}};return;}if(!inside(map,p.x,p.y))return;
  hover=p;keyboardCell=p;if(['fill','pick','spawn'].includes(tool)&&e.button!==2){applySingle(p);return;}beforeStroke=clone(map);gesture={kind:tool==='rectangle'&&e.button!==2?'rectangle':'draw',start:p,last:p,erase:e.button===2||tool==='erase'};if(gesture.kind==='draw')writeCell(p.x,p.y,gesture.erase);render();
}
function move(e){if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture?.kind==='touchpan'){const a=[...pointers.values()];if(a.length<2)return;viewport.scrollLeft=gesture.scroll.x+gesture.start.x-(a[0].x+a[1].x)/2;viewport.scrollTop=gesture.scroll.y+gesture.start.y-(a[0].y+a[1].y)/2;return;}if(gesture?.kind==='pan'){viewport.scrollLeft=gesture.scroll.x+gesture.start.x-e.clientX;viewport.scrollTop=gesture.scroll.y+gesture.start.y-e.clientY;return;}if(playing)return;const p=point(e);hover=inside(map,p.x,p.y)?p:null;if(hover)$('#cell-status').textContent=`Cell ${p.x}, ${p.y} · ${map.width} × ${map.height}`;
  if(gesture&&inside(map,p.x,p.y)){if(gesture.kind==='draw')for(const [x,y]of line(gesture.last.x,gesture.last.y,p.x,p.y))writeCell(x,y,gesture.erase);gesture.last=p;keyboardCell=p;}render();
}
function finishStroke(){if(gesture?.kind==='rectangle'&&beforeStroke){const a=gesture.start,b=gesture.last;for(let y=Math.min(a.y,b.y);y<=Math.max(a.y,b.y);y++)for(let x=Math.min(a.x,b.x);x<=Math.max(a.x,b.x);x++)writeCell(x,y);}if(beforeStroke)finishChange(beforeStroke);beforeStroke=null;gesture=null;render();}
function end(e){pointers.delete(e.pointerId);if(gesture?.kind==='touchpan'&&pointers.size>0)return;finishStroke();}
canvas.addEventListener('pointerdown',begin);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('lostpointercapture',e=>{pointers.delete(e.pointerId);if(!pointers.size)finishStroke();});canvas.addEventListener('pointerleave',()=>{if(!gesture){hover=null;render();}});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$$('[data-tool]').forEach(b=>b.onclick=()=>{if(!playing)setTool(b.dataset.tool);});$$('[data-layer]').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));$$('[data-category]').forEach(b=>b.onclick=()=>{if(!playing){category=b.dataset.category;palette();}});$$('[data-visible]').forEach(b=>b.onclick=()=>{if(playing)return;const l=b.dataset.visible;visible[l]=!visible[l];syncVisibility();render();});
async function changeMap(next,message){try{await loadCustom(next);map=next;if(selected>=1000&&(!map.custom||selected>=1000+map.custom.columns*map.custom.rows))selected=0;hover=null;keyboardCell={...map.spawn};dimensions();palette();syncHistory();autoSave();if(message)toast(message);}catch(e){toast(e.message);}}
async function undo(){if(playing)return;finishStroke();await changeMap(history.undo(map),'Undo applied.');}
async function redo(){if(playing)return;finishStroke();await changeMap(history.redo(map),'Redo applied.');}
$('#undo').onclick=undo;$('#redo').onclick=redo;
$('#map-name').addEventListener('change',()=>{if(playing){$('#map-name').value=map.name;return;}const before=clone(map);map.name=$('#map-name').value.trim()||'Untitled world';$('#map-name').value=map.name;$('.stage-tag').textContent=map.name.toUpperCase();finishChange(before);});
$('#resize-map').onclick=()=>{if(playing)return;try{finishStroke();const before=clone(map),next=resize(map,Number($('#map-width').value),Number($('#map-height').value));map=next;dimensions();finishChange(before,'Map resized. Undo restores any cropped tiles.');}catch(e){toast(e.message);}};
$('#grid').onclick=()=>{grid=!grid;$('#grid').setAttribute('aria-pressed',String(grid));render();};$('#fit').onclick=()=>{fitMap();render();};
function zoomBy(delta){stageFit=false;const old=zoom,cx=(viewport.scrollLeft+viewport.clientWidth/2)/old,cy=(viewport.scrollTop+viewport.clientHeight/2)/old;zoom=Math.max(.125,Math.min(4,Math.round((zoom+delta)*8)/8));applyZoom();viewport.scrollLeft=cx*zoom-viewport.clientWidth/2;viewport.scrollTop=cy*zoom-viewport.clientHeight/2;}
$('#zoom-in').onclick=()=>zoomBy(.25);$('#zoom-out').onclick=()=>zoomBy(-.25);
new ResizeObserver(()=>{if(stageFit){fitMap();render();}}).observe(viewport);
$('#new-map').onclick=()=>{if(!playing)$('#new-dialog').showModal();};$('#new-dialog').addEventListener('close',()=>{const choice=$('#new-dialog').returnValue;if(!['blank','garden'].includes(choice))return;finishStroke();const before=clone(map);map=choice==='garden'?starterMap():blankMap(map.width,map.height);selected=0;category='ground';layer='ground';setLayer('ground');dimensions();palette();finishChange(before,'New map ready. Undo returns to your previous world.');});
function filename(suffix){return(map.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'fieldwork-map')+suffix;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function saveJSON(){finishStroke();download(new Blob([JSON.stringify(map,null,2)],{type:'application/json'}),filename('.json'));toast('Project JSON saved — layers, collision and tiles included.');}
$('#save-json').onclick=saveJSON;$('#export-json').onclick=saveJSON;
$('#export-png').onclick=()=>{finishStroke();const out=document.createElement('canvas');out.width=map.width*32;out.height=map.height*32;renderArt(out.getContext('2d'));out.toBlob(blob=>{if(blob){download(blob,filename('.png'));toast('PNG saved with visible art layers. Guides and collision are excluded.');}else toast('PNG could not be created. Try again.');},'image/png');};
$('#tileset-export').onclick=()=>tileset.toBlob(blob=>{if(blob)download(blob,'fieldwork-tileset-32px.png');});
$('#open-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(playing){toast('End the walk test before opening a project.');return;}try{if(file.size>8*1024*1024)throw Error('Project JSON must be under 8 MB.');const next=validateMap(JSON.parse(await file.text()),tiles.length);await loadCustom(next);finishStroke();const before=clone(map);map=next;history.commit(before,map);await changeMap(next,'Project opened.');}catch(err){toast(err instanceof SyntaxError?'That file is not valid JSON.':err.message);}};
$('#tiles-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(playing){toast('End the walk test before importing tiles.');return;}try{if(!['image/png','image/webp'].includes(file.type)||file.size>4*1024*1024)throw Error('Choose a PNG or WebP under 4 MB.');const size=Number($('#import-size').value),url=URL.createObjectURL(file);let im;try{im=new Image();im.src=url;await im.decode();}finally{URL.revokeObjectURL(url);}if(im.width>2048||im.height>2048||im.width%size||im.height%size||im.width/size*im.height/size>256)throw Error('Use complete cells, up to 256 tiles and 2048 px per side. Check the cell size.');
    const out=document.createElement('canvas');out.width=im.width;out.height=im.height;out.getContext('2d').drawImage(im,0,0);const data=out.toDataURL('image/png');if(data.length>7_000_000)throw Error('The normalized tilesheet is too large. Use a smaller sheet.');await imageFrom(data);finishStroke();const before=clone(map);
    // Replacing a sheet clears only its old tile references, so no ID silently changes artwork.
    if(map.custom)for(const l of ['ground','objects'])map.layers[l]=map.layers[l].map(id=>id>=1000?-1:id);
    map.custom={data,size,columns:im.width/size,rows:im.height/size};selected=1000;category='custom';setLayer('ground');palette();finishChange(before,'Your tiles are ready. Replacing a custom sheet clears its previous placements; Undo restores them.');
  }catch(err){toast(err.message||'This image could not be opened.');}};
function startTest(){finishStroke();if(!visible.ground||!visible.objects){toast('Show both art layers before testing your world.');return;}if(!canStand(map,map.spawn.x+.5,map.spawn.y+.5)){toast('Spawn is blocked. Use the flag tool to place it on a clear tile.');return;}playing=true;hover=null;keys.clear();player={x:map.spawn.x+.5,y:map.spawn.y+.5,time:0,moving:false};$('#test-banner').hidden=false;viewport.classList.add('testing');$('#test-map').textContent='■ End walk test';$('#tool-status').textContent='Walk test · WASD / arrow keys';$$('.tools button,[data-category],[data-layer],.eye,#resize-map,#new-map,#map-name,#map-width,#map-height,#auto-solid,#import-size').forEach(el=>el.disabled=true);$('#open-file').disabled=true;$('#tiles-file').disabled=true;syncHistory();canvas.focus({preventScroll:true});render();toast('Move with WASD or arrows. On touch, tap a direction around your character.');}
function stopTest(){playing=false;player=null;keys.clear();$('#test-banner').hidden=true;viewport.classList.remove('testing');$('#test-map').textContent='▷ Test the map';$$('.tools button,[data-category],[data-layer],.eye,#resize-map,#new-map,#map-name,#map-width,#map-height,#auto-solid,#import-size').forEach(el=>el.disabled=false);$('#open-file').disabled=false;$('#tiles-file').disabled=false;syncHistory();setTool(tool);render();}
$('#test-map').onclick=()=>playing?stopTest():startTest();$('#stop-test').onclick=stopTest;
let touchDirection=null;
canvas.addEventListener('pointerdown',e=>{if(!playing||e.pointerType==='mouse')return;const r=canvas.getBoundingClientRect(),px=(e.clientX-r.left)*canvas.width/r.width/32,py=(e.clientY-r.top)*canvas.height/r.height/32;touchDirection={x:px-player.x,y:py-player.y};canvas.setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{touchDirection=null;});
function editingTarget(e){return /INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)||$('#new-dialog').open;}
document.addEventListener('keydown',e=>{
  if(e.key==='Escape'){if(playing)stopTest();else{finishStroke();hover=null;render();}return;}
  if(editingTarget(e))return;
  const key=e.key.toLowerCase();if(playing){if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();keys.add(key);}return;}
  if((e.ctrlKey||e.metaKey)&&key==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}
  if((e.ctrlKey||e.metaKey)&&key==='y'){e.preventDefault();redo();return;}
  if(e.ctrlKey||e.metaKey||e.altKey)return;
  if(e.code==='Space'){e.preventDefault();space=true;canvas.style.cursor='grab';return;}
  const tools={b:'paint',e:'erase',f:'fill',r:'rectangle',i:'pick',s:'spawn'};if(tools[key])setTool(tools[key]);
  if(key==='g')$('#grid').click();if(['arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();keyboardCell.x=Math.max(0,Math.min(map.width-1,keyboardCell.x+(key==='arrowright'?1:key==='arrowleft'?-1:0)));keyboardCell.y=Math.max(0,Math.min(map.height-1,keyboardCell.y+(key==='arrowdown'?1:key==='arrowup'?-1:0)));hover={...keyboardCell};render();}
  if(key==='enter'&&e.target===canvas){e.preventDefault();applySingle(keyboardCell);}
});document.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.code==='Space'){space=false;canvas.style.cursor='';}});window.addEventListener('blur',()=>{keys.clear();space=false;touchDirection=null;finishStroke();});
let last=performance.now();function tick(now){const dt=Math.min((now-last)/1000,.04);last=now;if(playing&&player){let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));if(touchDirection){dx=touchDirection.x;dy=touchDirection.y;}const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len;const step=3.3*dt;if(canStand(map,player.x+dx*step,player.y))player.x+=dx*step;if(canStand(map,player.x,player.y+dy*step))player.y+=dy*step;}player.moving=!!len;player.time+=dt;render();}requestAnimationFrame(tick);}requestAnimationFrame(tick);
async function init(){let restored=false;try{const saved=localStorage.getItem(KEY);if(saved){const next=validateMap(JSON.parse(saved),tiles.length);await loadCustom(next);map=next;restored=true;}}catch{toast('The previous browser save could not be opened. The garden is ready to edit.');}dimensions();palette();syncVisibility();setLayer('ground');setTool('paint');if(restored)toast('Your last world is back.');else autoSave();}await init();
