import {createState,getUnit,livingHeroes,livingEnemies,checkResult} from './state.js';
import {canAct,finishHero,nextRound,cooldown} from './turns.js';
import {abilities} from './characters.js';
import {move,attack,selfAbility,validTarget,damagePreview,targetsFor} from './combat.js';
import {planEnemy,enemyAction} from './ai.js';
import {tile,unitAt,distance,pathTo} from './grid.js';
import {createSprites,drawTile,drawProp} from './art.js';
import {Camera} from './camera.js';
import {Effects} from './effects.js';
import {AudioBus} from './audio.js';
import {Renderer} from './renderer.js?v=4';
import {movementPreview} from './preview.js';
import {UI,$,$$,helpHTML} from './ui.js?v=3';
let state=createState(),view={selected:'rowan',mode:'move',ability:null,hover:null,pending:null,busy:false,menu:true},screen='menu',paused=false,session=0,noticeTimer,pan=false,drag=null;
const canvas=$('#battlefield'),sprites=createSprites(),camera=new Camera(),effects=new Effects(),audio=new AudioBus(),renderer=new Renderer(canvas,sprites,camera,effects),ui=new UI(sprites,selectHero),keys=new Set();renderer.groundFn=drawTile;renderer.propFn=drawProp;
function notice(text){$('#notice').textContent=text;$('#notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('show'),4000);}
function update(){$('#route-preview').hidden=true;if(screen==='battle'||screen==='ended')ui.render(state,view);}
function setScreen(next){screen=next;document.body.dataset.screen=next;$('#title-screen').hidden=next!=='menu';$('#intro-screen').hidden=next!=='intro';$('#end-screen').hidden=next!=='ended';$('#battle-ui').hidden=!['battle','ended'].includes(next);$('#sidebar').hidden=!['battle','ended'].includes(next);$('#board-controls').hidden=next!=='battle';$('#pause-button').hidden=next!=='battle';view.menu=['menu','intro'].includes(next);$('#tooltip').hidden=true;$('#route-preview').hidden=true;}
function reset(){session++;effects.reset();state=createState();view={selected:'rowan',mode:'move',ability:null,hover:null,pending:null,busy:false,menu:true};camera.reset();renderer.hp.clear();keys.clear();paused=false;pan=false;$('#pan-toggle').setAttribute('aria-pressed','false');ui.lastLog='';ui.buildSquad(state);$('#phase-banner').classList.remove('show');$('#notice').classList.remove('show');}
async function startBattle(){const token=session;paused=false;setScreen('battle');view.menu=false;view.busy=true;update();canvas.focus({preventScroll:true});await banner('PLAYER PHASE');if(token!==session)return;view.busy=false;update();}
function mainMenu(){reset();setScreen('menu');$('#phase-text').textContent='A TACTICAL RPG';$('#phase-sub').textContent='WILD STROKES / ORIGINAL GAME';$('#turn-text').textContent='LAST STAND';}
function selectHero(id){if(screen!=='battle')return;if(view.busy||state.phase!=='player'){notice('The enemy is acting. Your squad moves next.');return;}const u=getUnit(state,id);if(!u||u.hp<=0)return;view.selected=id;view.mode=u.team==='hero'?'move':'inspect';view.ability=null;view.pending=null;view.hover=null;$('#tooltip').hidden=true;$('#route-preview').hidden=true;audio.play('select');update();}
function selectMode(mode){const u=getUnit(state,view.selected);if(!canAct(state,u)||view.busy)return;view.mode=mode;view.ability=null;view.pending=null;update();audio.play('select');}
async function banner(text){const el=$('#phase-banner');el.textContent=text;el.classList.toggle('enemy',text==='ENEMY PHASE');el.classList.add('show');await effects.wait(950);el.classList.remove('show');}
function eventFeedback(events,kind='hit'){for(const e of events){const u=getUnit(state,e.target);if(!u)continue;if(e.push)continue;effects.effect(e.shield?'shield':e.rage?'cry':kind,u.x,u.y,'',e.shield?'#a6d9d0':e.rage?'#d4a77d':kind==='fire'?'#efb175':'#eee1b1');effects.pose(u.id,e.shield||e.rage?'idle':'hurt',.35);if(e.amount>0)effects.effect('number',u.x,u.y,`${e.critical?'CRIT ':''}${e.amount}`,e.critical?'#f5d39b':'#e6e2bd');if(e.dead)effects.effect('death',u.x,u.y,u.id);}}
async function showResult(token){if(token!==session||screen!=='battle')return;await effects.wait(950);if(token!==session)return;setScreen('ended');view.busy=true;$('#end-screen').classList.toggle('defeat',state.result==='defeat');$('#end-title').textContent=state.result==='victory'?'VICTORY':'DEFEAT';$('#end-eyebrow').textContent=state.result==='victory'?'THE FORTRESS HOLDS.':'THE ASHEN CROWN HAS FALLEN.';$('#end-message').textContent=state.result==='victory'?'Three defenders stood against the ash. The last barrier remains.':state.crystal.hp===0?'The crown crystal shatters. Its light fades from Ashfall.':'The defenders fall. No one remains to hold the barrier.';$('#end-stats').innerHTML=[['TURNS TAKEN',state.round],['ENEMIES DEFEATED',state.kills],['HEROES REMAINING',livingHeroes(state).length],['CRYSTAL HEALTH',`${state.crystal.hp}%`]].map(([name,value])=>`<div><strong>${value}</strong><span>${name}</span></div>`).join('');$('#play-again').textContent=state.result==='victory'?'Play again':'Try again';audio.play(state.result);update();}
async function afterAction(token){if(token!==session)return;update();if(state.result){await showResult(token);return;}if(state.phase==='enemy')await enemyPhase(token);else{const selected=getUnit(state,view.selected);if(selected?.done||selected?.hp<=0){const next=livingHeroes(state).find(u=>!u.done);if(next){view.selected=next.id;view.mode='move';view.ability=null;}}update();}}
async function enemyPhase(token){view.busy=true;view.pending=null;update();await banner('ENEMY PHASE');if(token!==session)return;for(const enemy of [...livingEnemies(state)]){if(token!==session||state.result)break;view.selected=enemy.id;view.mode='inspect';update();const plan=planEnemy(state,enemy);if(!plan)continue;
    if(plan.path.length){const from={x:enemy.x,y:enemy.y};enemy.x=plan.goal.x;enemy.y=plan.goal.y;audio.play('step');await effects.walk(enemy,plan.path,from);if(token!==session)return;effects.effect('dust',enemy.x,enemy.y);}
    await effects.wait(240);if(token!==session)return;const target=getUnit(state,plan.target);if(target)effects.pose(enemy.id,'attack',.45);await effects.wait(180);if(token!==session)return;const result=enemyAction(state,enemy.id);audio.play(result.type==='arrow'?'arrow':result.type==='cry'?'cry':'slash');if(result.type==='slam'){effects.shake=7;effects.effect('slam',enemy.x,enemy.y,'','#e0b782');}eventFeedback(result.events,result.type==='arrow'?'arrow':'hit');update();await effects.wait(result.type==='cry'?650:500);}
  if(token!==session)return;if(checkResult(state)){await showResult(token);return;}nextRound(state);view.selected=livingHeroes(state)[0].id;view.mode='move';view.ability=null;update();await banner('PLAYER PHASE');if(token!==session)return;view.busy=false;update();
}
async function performMove(point){const u=getUnit(state,view.selected),from={x:u.x,y:u.y};let path;try{path=move(state,u.id,point);}catch(e){notice(e.message);return;}const token=session;view.busy=true;view.pending=null;update();audio.play('step');await effects.walk(u,path,from);if(token!==session)return;effects.effect('dust',u.x,u.y);view.busy=false;update();}
async function performAttack(){if(view.busy||!view.pending)return;const u=getUnit(state,view.selected),point={...view.pending},id=view.mode==='attack'?'basic':view.ability,valid=validTarget(state,u,point,id);if(!valid.ok){notice(valid.reason);return;}const token=session;view.busy=true;view.pending=null;update();effects.pose(u.id,'attack',.45);audio.play(id==='shield'?'shield':u.kind==='mage'?'fire':u.kind==='ranger'?'arrow':'slash');await effects.wait(230);if(token!==session)return;
  try{const events=attack(state,u.id,point,id);eventFeedback(events,u.kind==='mage'?'fire':u.kind==='ranger'?'arrow':'slash');for(const e of events.filter(e=>e.push)){const pushed=getUnit(state,e.target);await effects.walk(pushed,[e.to],e.from);if(token!==session)return;}update();await effects.wait(440);if(token!==session)return;view.busy=false;await afterAction(token);}catch(e){view.busy=false;notice(e.message);update();}
}
async function useSelf(id){if(view.busy)return;const u=getUnit(state,view.selected);try{const result=selfAbility(state,u.id,id);audio.play('shield');effects.effect('shield',u.x,u.y,'',result.step?'#bbd099':'#edd5a4');view.ability=null;view.mode='move';view.pending=null;const token=session;view.busy=true;update();await effects.wait(500);if(token!==session)return;view.busy=false;await afterAction(token);}catch(e){notice(e.message);}}
function waitHero(){const u=getUnit(state,view.selected);if(!canAct(state,u)||view.busy)return;view.pending=null;finishHero(state,u);afterAction(session);}
function worldPoint(event){const r=canvas.getBoundingClientRect(),h=Math.min(r.height,r.width*610/960),offset=(r.height-h)/2;return{x:(event.clientX-r.left)/r.width*960,y:(event.clientY-r.top-offset)/h*610};}
function hover(event){if(screen!=='battle'||view.busy||paused||drag){$('#tooltip').hidden=true;$('#route-preview').hidden=true;return;}const p=worldPoint(event),hit=renderer.pick(state,p.x,p.y,view);view.hover=hit;const target=hit&&(unitAt(state,hit.x,hit.y)||(hit.x===state.crystal.x&&hit.y===state.crystal.y?state.crystal:null)),u=getUnit(state,view.selected),tip=$('#tooltip');const route=view.mode==='move'&&u?movementPreview(state,u,hit):null;const routeLabel=$('#route-preview');routeLabel.hidden=!route;if(route)routeLabel.textContent=`${route.cost} movement · ${route.remaining} remaining after move`;if(!target){tip.hidden=true;return;}
  tip.hidden=false;tip.replaceChildren();const name=document.createElement('strong');name.textContent=target.name;const stats=document.createElement('p');stats.textContent=`HP ${target.hp} / ${target.maxHp}${target.attack?` · ATK ${target.attack} · MOVE ${target.move}`:''}`;tip.append(name,stats);if(canAct(state,u)&&['attack','ability'].includes(view.mode)&&target.team==='enemy'){const id=view.mode==='attack'?'basic':view.ability,check=validTarget(state,u,hit,id);const preview=document.createElement('p');preview.className='preview';preview.textContent=check.ok?`Expected damage: ${damagePreview(state,u,target,id)} · click to preview`:check.reason;tip.append(preview);}const stage=$('.stage').getBoundingClientRect();tip.style.left=`${Math.max(7,Math.min(stage.width-180,event.clientX-stage.left+14))}px`;tip.style.top=`${Math.max(7,Math.min(stage.height-90,event.clientY-stage.top-85))}px`;}
function clickBoard(event){if(screen!=='battle'||view.busy||paused||pan)return;canvas.focus({preventScroll:true});const p=worldPoint(event),hit=renderer.pick(state,p.x,p.y,view);if(!hit)return;const target=unitAt(state,hit.x,hit.y),u=getUnit(state,view.selected);
  // Shield targets and area spell centers take priority over hero selection.
  if(target?.team==='hero'&&!(view.mode==='ability'&&['shield','burst'].includes(view.ability))){selectHero(target.id);return;}
  if(!canAct(state,u)){if(target)selectHero(target.id);return;}
  if(view.mode==='move'){if(target?.team==='enemy'){selectHero(target.id);return;}if(tile(state,hit.x,hit.y)?.blocked){notice('Blocked terrain. Choose a green tile.');return;}performMove(hit);return;}
  if(['attack','ability'].includes(view.mode)){const id=view.mode==='attack'?'basic':view.ability;if(!id){notice('Choose an ability first.');return;}const check=validTarget(state,u,hit,id);if(!check.ok){notice(check.reason);return;}if(view.pending?.x===hit.x&&view.pending?.y===hit.y){performAttack();return;}view.pending={x:hit.x,y:hit.y};update();audio.play('select');return;}
  if(target)selectHero(target.id);
}
canvas.addEventListener('pointermove',e=>{if(drag){const p=worldPoint(e);camera.pan(p.x-drag.x,p.y-drag.y);drag=p;}else hover(e);});canvas.addEventListener('pointerleave',()=>{view.hover=null;$('#tooltip').hidden=true;$('#route-preview').hidden=true;});canvas.addEventListener('pointerdown',e=>{if(pan&&screen==='battle'){drag=worldPoint(e);canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointerup',()=>{drag=null;});canvas.addEventListener('pointercancel',()=>{drag=null;});canvas.addEventListener('click',clickBoard);canvas.addEventListener('wheel',e=>{if(screen!=='battle')return;e.preventDefault();camera.setZoom(e.deltaY<0?.1:-.1);},{passive:false});
$('#play-button').onclick=()=>{reset();setScreen('intro');audio.play('select');};$('#intro-continue').onclick=startBattle;$('#play-again').onclick=()=>{reset();startBattle();};$('#end-menu').onclick=mainMenu;
$('#action-move').onclick=()=>selectMode('move');$('#action-attack').onclick=()=>selectMode('attack');$('#action-ability').onclick=()=>selectMode(view.mode==='ability'?'move':'ability');$('#action-wait').onclick=waitHero;
$('#abilities-panel').addEventListener('click',e=>{const b=e.target.closest('[data-ability]');if(!b||b.disabled||view.busy)return;const id=b.dataset.ability,a=abilities[id];if(a.target==='self'){useSelf(id);return;}view.ability=id;view.pending=null;update();audio.play('select');});$('#confirm-attack').onclick=performAttack;$('#cancel-target').onclick=()=>{view.pending=null;update();};
$('#end-phase').onclick=()=>{if(view.busy||state.phase!=='player')return;const ready=livingHeroes(state).filter(u=>!u.done);if(!ready.length)return;$('#end-phase-message').textContent=`${ready.map(u=>u.name).join(', ')} ${ready.length===1?'has':'have'} not finished. They will wait this phase.`;paused=true;$('#end-phase-dialog').showModal();};$('#end-phase-dialog').addEventListener('close',()=>{paused=false;if($('#end-phase-dialog').returnValue==='end'){for(const u of livingHeroes(state).filter(u=>!u.done))finishHero(state,u);afterAction(session);}});
function pause(){if(screen!=='battle')return;paused=true;keys.clear();$('#pause-dialog').showModal();}$('#pause-button').onclick=pause;$('#resume-button').onclick=()=>$('#pause-dialog').close();$('#pause-dialog').addEventListener('close',()=>{paused=false;canvas.focus({preventScroll:true});});$('#restart-button').onclick=()=>{$('#pause-dialog').close();reset();startBattle();};$('#pause-menu').onclick=()=>{$('#pause-dialog').close();mainMenu();};
function info(content){$('#info-content').innerHTML=content;if(screen==='battle')paused=true;keys.clear();$('#info-dialog').showModal();}$('#how-to-play').onclick=()=>info(helpHTML);$('#battle-help').onclick=()=>info(helpHTML);$('#credits-button').onclick=()=>info('<p class="eyebrow">THE PEOPLE BEHIND THE FIELD</p><h2>Wild Strokes.</h2><p>Ashen Crown: Last Stand is an original art-and-code project for the Wild Strokes game development portfolio.</p><p>Characters, pixel terrain, interface icons and sound cues are drawn or synthesized by this project. Built with vanilla JavaScript and Canvas 2D, without external runtime libraries.</p><p>Explore the source for the combat rules, pathfinding, enemy behavior and artwork.</p><p><a href="https://github.com/strokeswild08/strokeswild08.github.io/tree/main/ashen-crown">Read the code ↗</a> · <a href="../projects/">More projects ↗</a></p>');$('#close-info').onclick=()=>$('#info-dialog').close();$('#info-dialog').addEventListener('close',()=>{paused=false;});
$('#audio-toggle').onclick=async()=>{const enabled=await audio.toggle();$('#audio-toggle').textContent=enabled?'Sound on':'Sound off';$('#audio-toggle').setAttribute('aria-pressed',String(enabled));};$('#camera-reset').onclick=()=>camera.reset();$('#zoom-plus').onclick=()=>camera.setZoom(.15);$('#zoom-minus').onclick=()=>camera.setZoom(-.15);$('#pan-toggle').onclick=()=>{pan=!pan;$('#pan-toggle').setAttribute('aria-pressed',String(pan));canvas.style.cursor=pan?'grab':'crosshair';};
document.addEventListener('keydown',e=>{if(['INPUT','BUTTON','SELECT'].includes(e.target.tagName)||$$('dialog').some(d=>d.open))return;const k=e.key.toLowerCase();if(screen!=='battle')return;if(k==='escape'){if(view.pending){view.pending=null;update();}else pause();return;}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);}if(view.busy)return;if(['1','2','3'].includes(k))selectHero(['rowan','lyra','kael'][Number(k)-1]);if(k==='m')selectMode('move');if(k==='t')selectMode('attack');if(k==='q')selectMode('ability');if(e.code==='Space'){e.preventDefault();waitHero();}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='battle'&&!paused)pause();});
let last=performance.now();function frame(now){const dt=Math.min(1,(now-last)/1000);last=now;if(!paused){effects.tick(dt);const x=Number(keys.has('a')||keys.has('arrowleft'))-Number(keys.has('d')||keys.has('arrowright')),y=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown'));if(x||y)camera.pan(x*dt*180,y*dt*180);camera.tick(dt);}renderer.render(state,view,dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);ui.buildSquad(state);setScreen('menu');
