import {icon,drawPortrait} from './art.js';
import {abilities,heroAbilities} from './characters.js';
import {getUnit,livingEnemies,livingHeroes} from './state.js';
import {canAct,cooldown} from './turns.js';
import {validTarget,damagePreview,targetsFor} from './combat.js';
export const $=s=>document.querySelector(s);
export const $$=s=>[...document.querySelectorAll(s)];
export class UI{
  constructor(sprites,select){this.sprites=sprites;this.select=select;this.lastLog='';for(const [id,label,image]of [['move','MOVE','move'],['attack','ATTACK','sword'],['ability','ABILITY','fire'],['wait','WAIT','wait']])$(`#action-${id}`).innerHTML=icon(image)+`<span>${label}</span>`;}
  buildSquad(s){$('#squad-cards').replaceChildren();for(const u of livingHeroes(s)){const b=document.createElement('button');b.className='squad-card';b.dataset.unit=u.id;b.setAttribute('aria-label',`Select ${u.name}`);const c=document.createElement('canvas');c.width=48;c.height=58;drawPortrait(c,this.sprites,u.kind);const info=document.createElement('div');info.innerHTML=`<strong>${u.name}</strong><small>${u.kind.toUpperCase()}</small><div class="hp-track"><span></span></div>`;const status=document.createElement('span');status.className='unit-state';b.append(c,info,status);b.onclick=()=>this.select(u.id);$('#squad-cards').append(b);}}
  render(s,v){$('#phase-text').textContent=s.result?'BATTLE COMPLETE':s.phase==='enemy'?'ENEMY PHASE':'PLAYER PHASE';$('#phase-dot').style.background=s.phase==='enemy'?'#c48a73':'#a4b783';$('#phase-sub').textContent=s.phase==='enemy'?(getUnit(s,v.selected)?.name||'THE ASH HOST ADVANCES').toUpperCase():'MOVE, THEN ONE ACTION PER HERO';$('#turn-text').textContent=`TURN ${String(s.round).padStart(2,'0')}`;
    $('#crystal-hp').textContent=`${s.crystal.hp} / 100`;$('#crystal-bar').style.width=`${s.crystal.hp}%`;const boss=getUnit(s,'commander');$('#boss-hp').textContent=`${boss.hp} / ${boss.maxHp}`;$('#boss-bar').style.width=`${boss.hp/boss.maxHp*100}%`;$('#enemies-left').textContent=`${livingEnemies(s).length} ENEMIES`;
    for(const b of $$('.squad-card')){const u=getUnit(s,b.dataset.unit);b.classList.toggle('active',v.selected===u.id);b.classList.toggle('fallen',u.hp<=0);b.disabled=s.phase!=='player'||v.busy||u.hp<=0;b.setAttribute('aria-pressed',String(v.selected===u.id));b.querySelector('.hp-track span').style.width=`${u.hp/u.maxHp*100}%`;b.querySelector('.unit-state').textContent=u.hp<=0?'FALLEN':u.done?'✓ DONE':`${u.hp} HP`;}const u=getUnit(s,v.selected)||livingHeroes(s)[0]||boss;
    $('#unit-title').textContent=`${u.kind.toUpperCase()}${u.team==='enemy'?' / ENEMY':''}`;$('#unit-name').textContent=u.name;$('#unit-hp').textContent=`${u.hp} / ${u.maxHp} HP`;$('#unit-hp-bar').style.width=`${u.hp/u.maxHp*100}%`;drawPortrait($('#portrait'),this.sprites,u.kind);
    $('#unit-stats').innerHTML=[['MOVE',u.team==='hero'?u.remaining:u.move],['ATK',u.attack],['DEF',u.defense+(u.guardUntil>=s.round?10:0)]].map(([label,value])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('');
    const available=canAct(s,u)&&!v.busy;for(const action of ['move','attack','ability','wait']){const b=$(`#action-${action}`);b.disabled=!available||(action==='move'&&u.remaining===0)||(action==='attack'&&!livingEnemies(s).some(e=>validTarget(s,u,e).ok));b.classList.toggle('active',v.mode===action&&available);b.setAttribute('aria-pressed',String(v.mode===action&&available));}
    $('#end-phase').disabled=s.phase!=='player'||v.busy||!!s.result;
    $('#action-help').textContent=u.team==='enemy'?`${u.weapon} · range ${u.range} · movement ${u.move}. Inspecting enemy stats.`:u.hp<=0?'This defender has fallen. The others can still hold the line.':u.done?'Turn complete. Choose another defender.':v.mode==='move'?`Movement remaining: ${u.remaining}. Click a green tile. Attacks and defensive abilities finish this turn.`:v.mode==='attack'?`${u.weapon} · range ${u.range}. Pick a target to preview, then confirm.`:v.mode==='ability'?'Choose an ability. Cooldowns count full rounds.':'Move, then attack or use an ability.';
    if(v.mode==='ability'&&available)this.abilityPanel(s,u,v);else $('#abilities-panel').hidden=true;
    $('#hint-text').textContent=v.busy?(s.phase==='enemy'?'Watch the enemy’s moves. Your defenders act next.':'Action in progress…'):s.round===1&&!u.done&&u.id==='rowan'?(u.x===1&&u.y===8?'Choose MOVE, then a green tile beside the nearby Raider.':'Choose ATTACK and target the nearby Raider.'):s.phase==='player'?`Protect the crystal. ${livingHeroes(s).filter(h=>!h.done).length} defenders still ready.`:'The enemy phase is underway.';
    const pending=v.pending&&available;if(pending){const id=v.mode==='attack'?'basic':v.ability,targets=targetsFor(s,u,v.pending,id);$('#target-panel').hidden=false;$('#target-name').textContent=id==='shield'?`Shield ${targets[0]?.name||'ally'}`:targets.map(t=>t.name).join(' + ');$('#target-damage').textContent=id==='shield'?'8 less incoming damage this phase':targets.map(t=>`${damagePreview(s,u,t,id)} damage`).join(' / ');$('#confirm-attack').textContent=id==='shield'?'Cast shield →':'Confirm attack →';}else $('#target-panel').hidden=true;
    const logText=s.log.slice(-4).join('|');if(logText!==this.lastLog){this.lastLog=logText;$('#log-list').replaceChildren();for(const item of s.log.slice(-4)){const li=document.createElement('li');li.textContent=item;$('#log-list').append(li);}}
  }
  abilityPanel(s,u,v){const p=$('#abilities-panel');p.hidden=false;p.replaceChildren();for(const [id,a]of heroAbilities(u)){const turns=cooldown(s,u,id),b=document.createElement('button');b.className='ability-card';b.classList.toggle('active',v.ability===id);b.dataset.ability=id;b.disabled=turns>0;b.innerHTML=icon(a.icon)+`<div><strong>${a.name}</strong><small>${turns?`COOLDOWN · ${turns} TURN${turns===1?'':'S'}`:`${a.damage?`${a.damage} POWER · `:''}${a.range?`RANGE ${a.range}`:'SELF'} · ${a.cooldown} TURN COOLDOWN`}</small><p>${a.description}</p></div>`;p.append(b);}}
}
export const helpHTML=`<p class="eyebrow">THE FIELD GUIDE</p><h2>Hold the crown court.</h2><p>Defeat the Dark Commander while keeping the crystal alive. If the crystal breaks or all three heroes fall, the battle is lost.</p><h3>YOUR TURN</h3><p>Select a hero, choose <strong>Move</strong>, then click a green tile. Movement follows open paths. You may split movement into smaller steps. Attack, a defensive ability or Wait finishes that hero’s turn. When everyone finishes, enemies act one at a time.</p><h3>THREE DEFENDERS</h3><p><strong>Rowan:</strong> armored frontline. Shield Bash pushes a foe; Guardian Stance adds defense.<br><strong>Lyra:</strong> long-range bow. Piercing Arrow needs a straight row or column. Quick Step grants 2 movement without spending her attack.<br><strong>Kael:</strong> ranged magic. Flame Burst hits a small area; Ember Shield protects one hero. Spells don’t hurt allies.</p><h3>BEFORE YOU STRIKE</h3><p>Click an orange tile to preview a target, then click it again or use Confirm. Walls block arrows and spells. Standing beside a wall, pillar or crate grants +3 defense against ranged physical attacks. Guards and shields expire at the next player phase. Cooldowns count complete rounds. Critical hits have a 10% chance and deal 1.5× damage.</p><h3>CONTROLS</h3><p>Click / tap to select and act. 1 / 2 / 3 selects heroes; M moves; T attacks; Q opens abilities; Space waits. WASD / arrows pan, mouse wheel or + / − zooms. Use Pan to drag the camera on touch. Escape pauses. Button labels show the available actions.</p><p>Roman Urdu: hero chuno, green tile par move karo, phir enemy ko select karke attack confirm karo. Crystal bachana zaroori hai. Lyra door se, Rowan samne se aur Kael area attacks se madad karta hai.</p>`;
